### ISSUE TITLE
Missing .env file?

### ISSUE THREAD

**Issue by clavoie** [ribice/goch#3]
Tried to follow your setup instructions to run locally, but I get this issue when running the docker compose command:

```
> docker-compose up --build
ERROR: Couldn't find env file: MY_GOPATH\src\github.com\ribice\goch\.env
```

I see that .env is in the .gitignore file, but referenced in the docker-compose.yml file, I am just wondering if that is the issue or if I am missing something.

Thank you for your help! Very excited to check out your project!

**Comment by ribice** [comment]
While testing I noticed this as well. I pushed an update that fixes this issue.

Normally I keep .env file in .gitignore, but since there isn't anything confidential I pushed it for ease of testing.
