### ISSUE TITLE
Go module support request

### ISSUE THREAD

**Issue by chaz8080** [ribice/goch#5]
With go mod support, you can:

* eliminate `/vendor`
* successfully run `./up` without having to adjust any Go envs, since dependencies will be installed by default to users' `GOPATH`

---

To convert to go modules from Gopkg:

```sh
cd goch
go mod init
go get
```

Running `go mod init` will create a `go.mod` file.
Running `go get` will generate your `go.sum` file. 

With those, you can safely get rid of:

* `/vendor`
* `Gopkg.lock`
* `Gopkg.toml`

**Comment by nealwashere** [comment]
https://github.com/ribice/goch/pull/6

**Comment by chaz8080** [comment]
thanks 👍
