### ISSUE TITLE
Can't reach this on the localhost:8080

### ISSUE THREAD

**Issue by morariu** [ribice/goch#9]
I'm just getting started with Golang. This looks great.

Just wondering if you could point into the right direction. I can't reach this on the localhost:8080

Issue below with go command not found, is it referring to the line 2 in the **up** file? Appreciate the time.

> ./up: 2: ./up: go: not found

> GOOS=linux CGO_ENABLED=0 go build -o goch .

` sudo ./up
./up: 2: ./up: go: not found
Starting goch...
Building goch
Step 1/4 : FROM yikaus/alpine-bash
 ---> c98c656004a8
Step 2/4 : RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
 ---> Using cache
 ---> 1d178928b654
Step 3/4 : ADD goch /
 ---> Using cache
 ---> 59f910a90085
Step 4/4 : ENTRYPOINT /goch
 ---> Using cache
 ---> 9d683bad10c7
Successfully built 9d683bad10c7
Successfully tagged goch_goch:latest
Starting goch_nats_stream_1 ... done
Starting goch_redis_1       ... done
Starting goch_goch_1        ... done
Attaching to goch_redis_1, goch_nats_stream_1, goch_goch_1
redis_1        | 1:C 27 May 2020 04:50:36.126 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1        | 1:C 27 May 2020 04:50:36.126 # Redis version=6.0.3, bits=64, commit=00000000, modified=0, pid=1, just started
nats_stream_1  | [1] 2020/05/27 04:50:36.194234 [INF] STREAM: Starting nats-streaming-server[test-cluster] version 0.17.0
nats_stream_1  | [1] 2020/05/27 04:50:36.194270 [INF] STREAM: ServerID: nGTtYw76Q6tSdgCXY6WexD
nats_stream_1  | [1] 2020/05/27 04:50:36.194276 [INF] STREAM: Go version: go1.13.7
nats_stream_1  | [1] 2020/05/27 04:50:36.194281 [INF] STREAM: Git commit: [f4b7190]
nats_stream_1  | [1] 2020/05/27 04:50:36.195443 [INF] Starting nats-server version 2.1.4
nats_stream_1  | [1] 2020/05/27 04:50:36.195461 [INF] Git commit [fb009af]
nats_stream_1  | [1] 2020/05/27 04:50:36.195846 [INF] Starting http monitor on 0.0.0.0:8222
nats_stream_1  | [1] 2020/05/27 04:50:36.195925 [INF] Listening for client connections on 0.0.0.0:4222
nats_stream_1  | [1] 2020/05/27 04:50:36.195931 [INF] Server id is NCXIXTJAGO6NTMRMBNHX37YKLQWM4LRPFRTYHU7R57FKTVAYUNTMEH7B
nats_stream_1  | [1] 2020/05/27 04:50:36.195934 [INF] Server is ready
redis_1        | 1:C 27 May 2020 04:50:36.126 # Configuration loaded
nats_stream_1  | [1] 2020/05/27 04:50:36.223499 [INF] STREAM: Recovering the state...
redis_1        | 1:M 27 May 2020 04:50:36.128 * Running mode=standalone, port=6379.
redis_1        | 1:M 27 May 2020 04:50:36.129 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1        | 1:M 27 May 2020 04:50:36.129 # Server initialized
nats_stream_1  | [1] 2020/05/27 04:50:36.224485 [INF] STREAM: Recovered 0 channel(s)
redis_1        | 1:M 27 May 2020 04:50:36.129 * Ready to accept connections
nats_stream_1  | [1] 2020/05/27 04:50:36.474956 [INF] STREAM: Message store is FILE
nats_stream_1  | [1] 2020/05/27 04:50:36.474974 [INF] STREAM: Store location: data
nats_stream_1  | [1] 2020/05/27 04:50:36.475007 [INF] STREAM: ---------- Store Limits ----------
nats_stream_1  | [1] 2020/05/27 04:50:36.475012 [INF] STREAM: Channels:            unlimited
nats_stream_1  | [1] 2020/05/27 04:50:36.475016 [INF] STREAM: --------- Channels Limits --------
nats_stream_1  | [1] 2020/05/27 04:50:36.475019 [INF] STREAM:   Subscriptions:          1000 *
nats_stream_1  | [1] 2020/05/27 04:50:36.475022 [INF] STREAM:   Messages     :       1000000 *
nats_stream_1  | [1] 2020/05/27 04:50:36.475025 [INF] STREAM:   Bytes        :     976.56 MB *
nats_stream_1  | [1] 2020/05/27 04:50:36.475029 [INF] STREAM:   Age          :     unlimited *
nats_stream_1  | [1] 2020/05/27 04:50:36.475031 [INF] STREAM:   Inactivity   :     unlimited *
nats_stream_1  | [1] 2020/05/27 04:50:36.475035 [INF] STREAM: ----------------------------------
nats_stream_1  | [1] 2020/05/27 04:50:36.475039 [INF] STREAM: Streaming Server is ready
goch_1         | 2020/05/27 04:50:37 starting server on port:8080
`

**Comment by ribice** [comment]
It seems you didn't have go installed / correct set on your path?

**Comment by morariu** [comment]
I believe that is correct. Thank you
